#ifndef REDMINECONNECTOR_GLOBAL_H
#define REDMINECONNECTOR_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(REDMINECONNECTOR_LIBRARY)
#  define REDMINECONNECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REDMINECONNECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REDMINECONNECTOR_GLOBAL_H

